# Utilisation d'une image Node.js
FROM node:18-alpine

# Définition du répertoire de travail
WORKDIR /app

# Copie des fichiers et installation des dépendances
COPY package.json package-lock.json ./
RUN npm install

# Copie du code source
COPY . .

# Exposer le port
EXPOSE 3003

# Commande pour démarrer l'application
CMD ["npm", "start"]
